[nfs]
172.31.92.137 ansible_ssh_user='ec2-user'

[webservers]
172.31.89.134 ansible_ssh_user='ec2-user'
172.31.85.131 ansible_ssh_user='ec2-user'

[db]
172.31.82.24 ansible_ssh_user='ec2-user' 

[lb]
172.31.93.2 ansible_ssh_user='ubuntu'