ssh[nfs]
44.204.87.243 ansible_ssh_user='ec2-user'

[webservers]
44.204.47.84 ansible_ssh_user='ec2-user'
44.211.63.203 ansible_ssh_user='ec2-user'

[db]
54.163.101.97 ansible_ssh_user='ec2-user' 

[lb]
3.90.41.56 ansible_ssh_user='ubuntu'