[nfs]
44.201.189.246 ansible_ssh_user='ec2-user'

[webservers]
54.197.22.105 ansible_ssh_user='ec2-user'
54.82.145.34 ansible_ssh_user='ec2-user'

[db]
184.72.82.27 ansible_ssh_user='ec2-user' 

[lb]
54.227.231.82 ansible_ssh_user='ubuntu'